---
- name: Install neutron client with DSCP support
  hosts: utility_all
  user: root

  tasks:
    - name: Install neutron client
      pip:
        name: "git+https://github.com/openstacknate/python-neutronclient.git@mitaka+dscp#egg=python-neutronclient"
        state: present
