# Goal of this play is to create two linux bridges:
#  * br-mgmt -> p3p1 - statically assigned mgmt network IP on the bridge
#  * br-vlan -> eth0 - link only to the provider network VLAN
#
---
- hosts: lab
  user: root
  vars:
    bridge_management_interface: p3p1
    bridge_vlan_interface: eth0
    bridge_netmask: 255.255.255.0
    bridge_gateway: 192.168.1.1

  tasks:
    - name: Drop the /etc/network/interfaces config
      template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        backup: Yes

    - name: Drop the /etc/network/interfaces.d/br-mgmt.cfg
      template:
        src: br-mgmt.cfg.j2
        dest: /etc/network/interfaces.d/br-mgmt.cfg
        backup: Yes
      notify:
        - ifup br-mgmt

    - name: Drop the /etc/network/interfaces.d/br-vlan.cfg
      template:
        src: br-vlan.cfg.j2
        dest: /etc/network/interfaces.d/br-vlan.cfg
        backup: Yes
      notify:
        - ifup br-vlan

  handlers:
    - name: ifup br-mgmt
      command: ifup br-mgmt

    - name: ifup br-vlan
      command: ifup br-vlan
