---
- hosts: lab
  user: ubuntu
  become: Yes

  vars:
    # OS packages that should be installed
    # on every target host. Note these packages
    # will not be installed within the LXC containers
    # created by OSA
    osa_target_host_packages:
      - linux-generic-lts-xenial
      - bridge-utils
      - debootstrap
      - ifenslave
      - ifenslave-2.6
      - lsof
      - lvm2
      - ntp
      - ntpdate
      - openssh-server
      - sudo
      - tcpdump
      - vlan
      - sysstat
      - conntrack
      - lldpd
      - iftop

    osa_target_host_kernel_modules:
      - bonding
      - 8021q

    # public keys of users who should be able
    # to ssh as root to the target hosts
    osa_target_host_ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMbl/20hYXBM5VsCU01zv4rc7coO8D5xE56j/GqTv/VJ+iEJrulU/it50SE08j80F++M2ARWN90X8q8I6J7AaIh3q4qZXK2qR3mTt8gD950Kst28x4UyM2XdkCR2T3315d250JQyR6hh8Z8Xzdqn1y/upUeWEdyUCevTl1mPi1XUKbB0qYoByn2MXWryw9hWwqqASE0ScRMKETIpQxw9VG7KbaImWMosYSJRZ2a10mNcrVWDbechO1YNYsLcdylXeD4zfkhK0Fq3VLUoGOrPDrlKW45A9u1b9G/CPgzmno5YFKrXBcCs/p6DYzhkGt+h2u4OUZtYhEY0/OJuCaQw5L lab@charles_lab"

  tasks:
    - name: do apt-get dist-upgrade
      apt:
        update_cache: yes
        state: latest
        upgrade: dist

    - name: Install package(s) required by OSA
      apt:
        pkg: "{{ item }}"
        state: present
      with_items: "{{ osa_target_host_packages }}"

    - name: Allow OSA to ssh to target hosts as root
      authorized_key:
        user: root
        key: "{{ item }}"
      with_items: "{{ osa_target_host_ssh_keys }}"

    - name: Ensure kernel modules
      modprobe:
        name: "{{ item }}"
      with_items: "{{ osa_target_host_kernel_modules }}"

    - name: Ensure kernel modules loaded at boot
      lineinfile:
        dest: /etc/modules
        line: "{{ item }}"
      with_items: "{{ osa_target_host_kernel_modules }}"

- include: bridge-config.yml
- include: dns.yml
