---
- hosts: lab
  user: ubuntu
  become: Yes

  vars:
    # OS packages that should be installed
    # on every target host. Note these packages
    # will not be installed within the LXC containers
    # created by OSA
    osa_target_host_packages:
      - linux-generic-lts-xenial
      - bridge-utils
      - debootstrap
      - ifenslave
      - ifenslave-2.6
      - lsof
      - lvm2
      - ntp
      - ntpdate
      - openssh-server
      - sudo
      - tcpdump
      - vlan
      - sysstat
      - conntrack
      - lldpd
      - iftop

    osa_target_host_kernel_modules:
      - bonding
      - 8021q

    # public keys of users who should be able
    # to ssh as root to the target hosts
    osa_target_host_ssh_keys: []

  tasks:
    - name: do apt-get dist-upgrade
      apt:
        update_cache: yes
        state: latest
        upgrade: dist

    - name: Install package(s) required by OSA
      apt:
        pkg: "{{ item }}"
        state: present
      with_items: "{{ osa_target_host_packages }}"

    - name: Allow OSA to ssh to target hosts as root
      authorized_key:
        user: root
        key: "{{ item }}"
      with_items: "{{ osa_target_host_ssh_keys }}"

    - name: Ensure kernel modules
      modprobe:
        name: "{{ item }}"
      with_items: "{{ osa_target_host_kernel_modules }}"

    - name: Ensure kernel modules loaded at boot
      lineinfile:
        dest: /etc/modules
        line: "{{ item }}"
      with_items: "{{ osa_target_host_kernel_modules }}"